<#
.SYNOPSIS
    Generates the printable voice-over recording sheet from the localization data.

.DESCRIPTION
    Joins game/localization/vo.csv (the single source of truth for line text) with
    tools/vo-directions.csv (performance notes) and writes docs/VO_SCRIPT.md.

    The script text is never duplicated by hand — edit vo.csv and re-run this.

.PARAMETER Locale
    Which language sheet to produce: en, fr, or both (default).

.EXAMPLE
    pwsh tools/Build-VoSheet.ps1 -Locale fr
#>
[CmdletBinding()]
param(
    [ValidateSet('en', 'fr', 'both')]
    [string]$Locale = 'both'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

$lines = Import-Csv (Join-Path $root 'game/localization/vo.csv') -Encoding UTF8
$directions = @{}
Import-Csv (Join-Path $root 'tools/vo-directions.csv') -Encoding UTF8 | ForEach-Object {
    $directions[$_.keys] = $_
}

$locales = if ($Locale -eq 'both') { @('en', 'fr') } else { @($Locale) }

# Built from char codes rather than written literally: this file must stay pure ASCII
# so Windows PowerShell 5.1 (which reads .ps1 as ANSI) parses it identically to pwsh 7.
$localeNames = @{ en = 'English'; fr = "Fran$([char]0xE7)ais" }
$emDash = [char]0x2014

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# PostalBen $emDash Voice-over recording script")
[void]$sb.AppendLine()
[void]$sb.AppendLine("> Generated by ``tools/Build-VoSheet.ps1``. Do not edit by hand $emDash")
[void]$sb.AppendLine('> edit `game/localization/vo.csv` (text) or `tools/vo-directions.csv` (direction) and re-run.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('## How to record')
[void]$sb.AppendLine()
[void]$sb.AppendLine('1. Record each line as its own take. One file per key.')
[void]$sb.AppendLine('2. Name the file exactly the key, `.wav`: `ben.wake.day1.wav`.')
[void]$sb.AppendLine("3. Drop files into ``audio-raw/<locale>/`` at the repo root (git-ignored $emDash raw takes are big).")
[void]$sb.AppendLine('4. Run `pwsh tools/Normalize-Vo.ps1 -Locale <locale>` to convert, trim and level them into the game.')
[void]$sb.AppendLine("5. Leave 1s of silence at the head and tail of each take $emDash the normalizer trims it and needs the room tone.")
[void]$sb.AppendLine()
[void]$sb.AppendLine("Mono, 48 kHz, 24-bit WAV. Pop filter. Same mic position for the whole session $emDash")
[void]$sb.AppendLine('lines from different sessions sit next to each other in-game and tone shifts are audible.')
[void]$sb.AppendLine()

foreach ($loc in $locales) {
    [void]$sb.AppendLine("---")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("## $($localeNames[$loc]) (``$loc``)")
    [void]$sb.AppendLine()

    $bySpeaker = $lines | Group-Object { ($directions[$_.keys]).speaker }

    foreach ($group in $bySpeaker | Sort-Object Name) {
        [void]$sb.AppendLine("### Speaker: ``$($group.Name)``")
        [void]$sb.AppendLine()

        foreach ($line in $group.Group) {
            $key = $line.keys
            $text = $line.$loc
            $dir = ($directions[$key]).direction

            [void]$sb.AppendLine("#### ``$key``")
            [void]$sb.AppendLine()
            [void]$sb.AppendLine("> $text")
            [void]$sb.AppendLine()
            if ($dir) { [void]$sb.AppendLine("*Direction: $dir*") }
            [void]$sb.AppendLine()
        }
    }
}

$total = ($lines | Measure-Object).Count
[void]$sb.AppendLine("---")
[void]$sb.AppendLine()
$takes = $total * $locales.Count
[void]$sb.AppendLine("**$total lines per language $emDash $takes takes total for this sheet.**")

$out = Join-Path $root 'docs/VO_SCRIPT.md'
$sb.ToString() | Out-File -FilePath $out -Encoding utf8
Write-Host "Wrote $out ($total lines, $($locales.Count) locale(s))"
